parameters:
    hoa.notification_service.class: HOA\Bundle\NotificationBundle\Services\NotificationService
    hoa.twilio_service.class: HOA\Bundle\NotificationBundle\Services\TwilioService
    hoa.mailer_service.class: HOA\Bundle\NotificationBundle\Services\MailerService

services:
    hoa.twilio.api:
        class: %hoa.twilio_service.class%
        arguments: [ "%hoa_notification.sms_service.twilio%","@twig", "%hoa_notification.sms_service.active%" ]

    hoa.mailer:
      class: %hoa.mailer_service.class%
      arguments: ["@mailer", "@twig", "%hoa_notification.mailer_service.hoa_from_email%","%hoa_notification.mailer_service.hoa_bcc_email%"]

    hoa.notification:
        class: %hoa.notification_service.class%
